# Author:  Tan Menglong <tanmenglong@gmail.com>
# Date:    Tue Apr  2 14:51:21 2013
#
# Make Target:
# ------------
# The Makefile provides the following targets to make:
#   $ make           compile and link
#   $ make clean     clean objects and the executable file
#
#===========================================================================

all :
	make -C sort
	make -C dp

clean :
	make clean -C sort
	make clean -C dp
